---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcloud-pvc
spec:
  volumeName: gcloud-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
