apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: adrabenche/k8s-the-practical-guide:214
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: temp-volume
          emptyDir: {}
        - name: story-volume
          persistentVolumeClaim:
            claimName: gcloud-pvc
