apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
  deletionGracePeriodSeconds: 10
  labels:
    app: story
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: adrabenche/k8s-the-practical-guide:212